auction/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
# from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'catalog/', include('catalog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    # url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^lots/$', views.LotListView.as_view(), name='lots'),
    url(r'^lot/(?P<pk>\d+)$', views.LotDetailView.as_view(), name='lot-detail'),
    url(r'^auctions/$', views.AuctionListView.as_view(), name='auctions'),
    url(r'^auction/(?P<pk>\d+)$', views.AuctionDetailView.as_view(), name='auction-detail'),
    url(r'^mylots/$', views.LotsForSaleByUserListView.as_view(), name='my-for-sale'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
import datetime


class Category(models.Model):
    """
    Model representing a category of auction (e.g. Charity, Electronics etc.).
    """

    name = models.CharField(max_length=200, help_text="Enter a category of auction (e.g. Charity, Electronics etc.)")

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ["name"]

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

'''
class User(AbstractUser):
    account = models.DecimalField(max_digits=10, decimal_places=1, blank=False, null=True)
    favourites = models.ManyToManyField(Category, null=True)

    def __str__(self):
        return self.username
'''

class Auction(models.Model):
    name = models.CharField(max_length=200, help_text="Enter an auction name")
    start_time = models.DateTimeField(help_text="Enter a starting time")
    duration = models.DurationField(help_text="Enter a duration time")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                 help_text="Select a category for this auction")

    @property
    def finish_time(self):
        return self.start_time + self.duration

    class Meta:
        ordering = ["name", "start_time"]

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('auction-detail', args=[str(self.id)])


class Lot(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a lot name")
    start_price = models.DecimalField(max_digits=10, decimal_places=1, blank=False, null=False,
                                      help_text="Enter a starting price")
    start_time = models.DateTimeField(help_text="Enter a starting time")
    duration = models.DurationField(help_text="Enter a duration time eg 3d 2:20:10")
    step = models.DecimalField(max_digits=5, decimal_places=1, blank=False, null=False,
                               help_text="Enter a starting price")
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    # Foreign Key used because lot can only have one auction, but auctions can have multiple lots
    auction = models.ForeignKey(Auction, on_delete=models.SET_NULL, null=True)
    is_on_auction = models.BooleanField(default=False)
    is_sold = models.BooleanField(default=False)

    @property
    def finish_time(self):
        return self.start_time + self.duration

    @property
    def is_valid_for_buying(self):
        if not self.is_sold and datetime.datetime.now() > self.finish_time:
            return True
        return False

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('lot-detail', args=[str(self.id)])

catalog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import Auction, Lot
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_auctions = Auction.objects.all().count()
    num_lots = Lot.objects.all().count()
    # Непроданные лоты
    # num_lots_available = Lot.objects.filter(is_sold='True').count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_auctions': num_auctions, 'num_lots': num_lots, 'num_visits': num_visits},
    )


class LotListView(generic.ListView):
    model = Lot
    paginate_by = 10


class LotDetailView(generic.DetailView):
    model = Lot


class AuctionListView(generic.ListView):
    model = Auction
    paginate_by = 10


class AuctionDetailView(generic.DetailView):
    model = Auction


class LotsForSaleByUserListView(LoginRequiredMixin, generic.ListView):
    model = Lot
    template_name = 'catalog/lot_list_for_sale.html'
    paginate_by = 5

    def get_queryset(self):
        return Lot.objects.filter(seller=self.request.user).filter(is_sold='False').order_by('name')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Auction Trading Center</title>{% endblock %}
    <meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'auctions' %}">All auctions</a></li>
          <li><a href="{% url 'lots' %}">All lots</a></li>
      </ul>
      <ul class="sidebar-nav">
            {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="">My favourite categories</a></li>
                <li><a href="{% url 'my-for-sale' %}">My lots on auction</a></li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
          {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
                                                                                                                                                                                                                                                                                                                                                                                                {% endblock %}
      </div>
    </div>

  </div>

</body>
</html>

catalog/templates/catalog/auction_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ auction.name }}</h1>

  <p><strong>Start at:</strong> {{ auction.start_time }}</p>
  <p><strong>Duration:</strong> {{ auction.duration }}</p>
  <p><strong>Category:</strong> {{ auction.category }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Lots:</h4>

    <ul>
        {% for cur_lot in auction.lot_set.all %}

            <li><a href="{% url 'lot-detail' cur_lot.id %}">{{cur_lot.name}}</a></li>
            <hr>
        {% endfor %}
    </ul>

  </div>
{% endblock %}

catalog/templates/catalog/auction_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Auction List</h1>

    {% if auction_list %}
    <ul>

      {% for auction in auction_list %}
      <li>
        <a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no auctions yet.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ category.name }}</h1>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Auctions:</h4>

    <ul>
        {% for cur_auction in category.auction_set.all %}

            <li><a href="{% url 'auction-detail' cur_auction.id %}">{{cur_auction.name}}</a></li>
            <hr>
        {% endfor %}
    </ul>

  </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Category List</h1>

    {% if category_list %}
    <ul>

      {% for category in category_list %}
      <li>
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no categories yet.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/lot_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ lot.name }}</h1>

    <p><strong>Auction:</strong> <a href="{% url 'auction-detail' lot.auction.pk %}">{{ lot.auction }}</a></p>
    <p><strong>Start from:</strong> {{ lot.start_price }}</p>
    <p><strong>Start at:</strong> {{ lot.start_time }}</p>
    <p><strong>Duration:</strong> {{ lot.duration }}</p>
    <p><strong>Step:</strong> {{ lot.step }}</p>
    <p><strong>Seller:</strong> {{ lot.seller }}</p>
{% endblock %}

catalog/templates/catalog/lot_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lot List</h1>

    {% if lot_list %}
    <ul>

      {% for lot in lot_list %}
      <li>
        <a href="{{ lot.get_absolute_url }}">{{ lot.name }}</a> ({{lot.auction}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no lots yet.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/lot_list_for_sale.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lots for sale</h1>

    {% if lot_list %}
    <ul>

      {% for lot in lot_list %}
      <li>
        <a href="{{ lot.get_absolute_url }}">{{ lot.name }}</a> ({{lot.auction}})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no lots for sale yet.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Auction Trading Center Home</h1>

  <p>Welcome to <em>Auction Trading Center</em></p>

<h2>Dynamic content</h2>

  <p>The auction has the following record counts:</p>
  <ul>
    <li><strong>Auctions:</strong> {{ num_auctions }}</li>
    <li><strong>Lots:</strong> {{ num_lots }}</li>
    <!--<li><strong>Lots available:</strong> {{ num_lots_available }}</li>-->
  </ul>

  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}